### ISSUE TITLE
AMI from existing EC2 instance

### ISSUE THREAD

**Issue by zaro0508** [PokaInc/cloudformation-ami#4]
Was wondering if there is an option to create an AMI from an existing EC2 instance?

**Comment by spg** [comment]
You can do this in the EC2 console. See https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/creating-an-ami-ebs.html

**Comment by zaro0508** [comment]
thanks @spg,  i am aware of that but I prefer to use cloudformation.  I would like to use your project to create AMI instead.  I think see how it can be done now.  I just need to pass my custom instance  into the TemplateInstance dict using `ImageId` parameter.   Thanks for this project.
